### PR TITLE
Add blit() method for speedy frame updates

### PR DESCRIPTION
**Pull request by mordyovits**
I found that even in a simple, tight loop, filling a frame with pixel() calls is too slow.  This blit() function allow a caller pass in a bytearray of brightness ("color") data and the frame number to be written to.  It validates that the passed bytearray won't overflow that frame's region, but allows for shorter lengths.  It also doesn't do coordinate math (e.g for 15x7 CharlieWing devices); that's left up to the caller to know.

It's a radically faster overwrite than the pixel() method, allowing for animation, even non-double buffered (with frame()) calls.

### CODE REVIEW

**Review by deshipu — APPROVED** [review]
Looks good to me. I'm not sure about calling the method "blit", because blit usually lets you specify coordinates and size, etc., but that's nit-picking.

**Comment by deshipu** [comment]
@mordyovits do you think you could rename that function to something like ``write_frame`` to avoid confusion with the BLIT operation?

**Comment by mordyovits** [comment]
Of course.  I'll take care of it tonight.

**Comment by mordyovits** [comment]
@deshipu Done, as per your request.  I also added documentation for the method.

**Review by deshipu — APPROVED** [review]

**Comment by deshipu** [comment]
Thank you!

**Pull request merged**
